name: 🐛 Bug
description: Report an issue to help improve the project.
title: "<description>"
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue, also include what you tried and what didn't work
      value: |
        ### What is the problem you are facing
        
        ### What is your suggested solution
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable (NOT of code!)
    validations:
      required: false
