name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
title: '<description>'
labels: documentation
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable (NOT of code!)
    validations:
      required: false
