name: 🌟 Feature Request
description: Have a new idea/feature for this project? Please suggest!
title: '<description>'
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose, also include what you tried and what worked.
      value: |
        ### What kind of feature you are suggesting?
        
        ### Does it solve any problem?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable (NOT of code!)
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
