name: Deploy to host server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - '.env'
      - 'jsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: 🔧 Create build
        run: |
          npm install
          npm run build
      - name: 🚀 Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ vars.HOST_USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build"
          target: "${{ vars.HOST_TARGET_DIR }}"
          strip_components: 1
          rm: true
